import { Lead, IncomeEntry } from "./types";

const today = new Date();
const thisMonth = today.getMonth();
const thisYear = today.getFullYear();

const getDateInMonth = (day: number) => {
  return new Date(thisYear, thisMonth, day).toISOString().split("T")[0];
};

export const dummyLeads: Lead[] = [
  {
    id: "lead-001",
    clientName: "Ahmed Hassan - Real Estate Developer",
    niche: "Real Estate Marketing",
    sourceAgency: "Domya",
    status: "Meeting",
    dealValue: 50000,
    expectedCommission: 5000,
    nextFollowUpDate: getDateInMonth(10),
    notes:
      "Very interested in digital marketing for new compound launch in Sheikh Zayed. Meeting scheduled to present full campaign strategy. Decision maker confirmed attendance.",
    phone: "+20 100 234 5678",
    email: "ahmed.hassan@realestate-dev.com",
    createdAt: getDateInMonth(1),
  },
  {
    id: "lead-002",
    clientName: "Nour Ali - E-commerce Store Owner",
    niche: "E-commerce",
    sourceAgency: "Krijo",
    status: "Proposal Sent",
    dealValue: 35000,
    expectedCommission: 3500,
    nextFollowUpDate: getDateInMonth(12),
    notes:
      "Sent proposal for Instagram ads and Shopify optimization. Store sees 5k monthly visitors. Waiting for budget approval from partner.",
    phone: "+20 111 876 5432",
    email: "nour.ali@shopnow.eg",
    createdAt: getDateInMonth(3),
  },
  {
    id: "lead-003",
    clientName: "Dr. Laila Karim - Medical Clinic",
    niche: "Healthcare",
    sourceAgency: "Personal",
    status: "Closed",
    dealValue: 15000,
    expectedCommission: 2250,
    nextFollowUpDate: getDateInMonth(15),
    notes:
      "Completed Facebook and Google Ads campaign for plastic surgery clinic. ROAS reached 4.2x in first month. Client requested renewal proposal for Q3.",
    phone: "+20 122 345 6789",
    email: "dr.laila@klinik-karim.com",
    createdAt: getDateInMonth(2),
  },
  {
    id: "lead-004",
    clientName: "Fatima Mostafa - Fashion Brand",
    niche: "Fashion & Retail",
    sourceAgency: "Krijo",
    status: "Follow-up",
    dealValue: 28000,
    expectedCommission: 2800,
    nextFollowUpDate: getDateInMonth(9),
    notes:
      "Initial consultation done. Following up on brand strategy proposal for summer collection launch. She mentioned budget is ready.",
    phone: "+20 101 555 7890",
    email: "fatima@modabyf.com",
    createdAt: getDateInMonth(4),
  },
  {
    id: "lead-005",
    clientName: "Mohamed Samir - Tech Startup",
    niche: "Technology",
    sourceAgency: "Freelance",
    status: "Contacted",
    dealValue: 42000,
    expectedCommission: 4200,
    nextFollowUpDate: getDateInMonth(11),
    notes:
      "First contact via LinkedIn. B2B SaaS product targeting HR departments. Interested in growth hacking and LinkedIn Ads. Booked discovery call for next week.",
    phone: "+20 100 998 7654",
    email: "m.samir@techvision.io",
    createdAt: getDateInMonth(5),
  },
  {
    id: "lead-006",
    clientName: "Hana Khalil - Coffee Roastery",
    niche: "Food & Beverage",
    sourceAgency: "Domya",
    status: "New Lead",
    dealValue: 20000,
    expectedCommission: 2000,
    nextFollowUpDate: getDateInMonth(13),
    notes:
      "Referral from Dr. Laila. Specialty coffee brand wants to expand from wholesale to D2C online sales. Great Instagram presence already (22k followers).",
    phone: "+20 115 432 1098",
    email: "hana@beanroast.eg",
    createdAt: getDateInMonth(6),
  },
  {
    id: "lead-007",
    clientName: "Karim Elsayed - Gym Chain",
    niche: "Fitness & Wellness",
    sourceAgency: "Personal",
    status: "Proposal Sent",
    dealValue: 32000,
    expectedCommission: 3200,
    nextFollowUpDate: getDateInMonth(14),
    notes:
      "Sent comprehensive digital marketing proposal for 3 branches expansion in Cairo. Includes influencer strategy, Google Maps ads, and membership campaign.",
    phone: "+20 109 876 5432",
    email: "karim@ironbody-eg.com",
    createdAt: getDateInMonth(1),
  },
  {
    id: "lead-008",
    clientName: "Yasmin Adel - Interior Design Studio",
    niche: "Interior Design",
    sourceAgency: "Domya",
    status: "Lost",
    dealValue: 18000,
    expectedCommission: 0,
    nextFollowUpDate: getDateInMonth(16),
    notes:
      "Client chose competitor offering a lower price. Will follow up in 3 months — competitor contracts often end badly. Keep warm.",
    phone: "+20 122 765 4321",
    email: "yasmin@artspace-id.com",
    createdAt: getDateInMonth(2),
  },
  {
    id: "lead-009",
    clientName: "Omar Shawky - Restaurant Chain",
    niche: "Food & Beverage",
    sourceAgency: "Krijo",
    status: "Meeting",
    dealValue: 45000,
    expectedCommission: 4500,
    nextFollowUpDate: getDateInMonth(8),
    notes:
      "Chain of 5 Egyptian cuisine restaurants planning Ramadan campaign. Meeting confirmed at their Zamalek branch. They want TikTok + Meta strategy.",
    phone: "+20 100 321 9876",
    email: "omar@shawkygroup.com",
    createdAt: getDateInMonth(3),
  },
  {
    id: "lead-010",
    clientName: "Rania Ibrahim - Online Education Platform",
    niche: "Education",
    sourceAgency: "Domya",
    status: "Closed",
    dealValue: 38000,
    expectedCommission: 3800,
    nextFollowUpDate: getDateInMonth(20),
    notes:
      "EdTech platform for K-12 tutoring. Campaign drove 2,300 new student signups in 6 weeks. Client thrilled — already talking about scaling budget x2.",
    phone: "+20 111 654 3210",
    email: "rania@learnwithme.eg",
    createdAt: getDateInMonth(1),
  },
  {
    id: "lead-011",
    clientName: "Tarek Mostafa - Photography Studio",
    niche: "Photography & Media",
    sourceAgency: "Freelance",
    status: "Follow-up",
    dealValue: 12000,
    expectedCommission: 1200,
    nextFollowUpDate: getDateInMonth(7),
    notes:
      "Needs Google Ads + Instagram presence to attract corporate event clients. Price sensitive but has long-term potential. Sent revised lower-tier proposal.",
    phone: "+20 100 111 2233",
    email: "tarek@shuttermoment.com",
    createdAt: getDateInMonth(5),
  },
  {
    id: "lead-012",
    clientName: "Sara Mahmoud - Dental Clinic Group",
    niche: "Healthcare",
    sourceAgency: "Personal",
    status: "New Lead",
    dealValue: 25000,
    expectedCommission: 3750,
    nextFollowUpDate: getDateInMonth(11),
    notes:
      "3 clinic locations in Maadi and Heliopolis. Looking for full digital presence setup: Google Ads, SEO, social media management. Got contact via mutual friend.",
    phone: "+20 122 887 6543",
    email: "sara@smilemore-clinics.com",
    createdAt: getDateInMonth(7),
  },
  {
    id: "lead-013",
    clientName: "Hassan Fawzy - Car Dealership",
    niche: "Automotive",
    sourceAgency: "Domya",
    status: "Proposal Sent",
    dealValue: 60000,
    expectedCommission: 6000,
    nextFollowUpDate: getDateInMonth(9),
    notes:
      "Largest Hyundai sub-dealer in Alexandria. Wants to dominate online used car search. Proposal covers Meta Leads Ads + Google Search + Inventory remarketing.",
    phone: "+20 100 444 7788",
    email: "h.fawzy@fawzy-motors.com",
    createdAt: getDateInMonth(2),
  },
  {
    id: "lead-014",
    clientName: "Mona El-Sayed - Wedding Planning Co.",
    niche: "Events & Entertainment",
    sourceAgency: "Krijo",
    status: "Contacted",
    dealValue: 22000,
    expectedCommission: 2200,
    nextFollowUpDate: getDateInMonth(13),
    notes:
      "Boutique wedding planner targeting upper-middle segment. Reached out via email after seeing similar client work. Intro call went well — very clear on what she wants.",
    phone: "+20 111 234 5670",
    email: "mona@blissful-weddings.eg",
    createdAt: getDateInMonth(6),
  },
  {
    id: "lead-015",
    clientName: "Sherif Khalil - Import/Export Co.",
    niche: "B2B Services",
    sourceAgency: "Personal",
    status: "Meeting",
    dealValue: 55000,
    expectedCommission: 5500,
    nextFollowUpDate: getDateInMonth(6),
    notes:
      "B2B trading company that wants to attract international buyers through LinkedIn and Google. First time doing digital marketing — high potential. Meeting with CEO directly.",
    phone: "+20 100 789 0123",
    email: "sherif@khaliltrading.com",
    createdAt: getDateInMonth(4),
  },
  {
    id: "lead-016",
    clientName: "Dina Aziz - Spa & Beauty Center",
    niche: "Beauty & Wellness",
    sourceAgency: "Domya",
    status: "Follow-up",
    dealValue: 18000,
    expectedCommission: 1800,
    nextFollowUpDate: getDateInMonth(10),
    notes:
      "Day spa in New Cairo wants to increase appointment bookings 3x. Proposal sent for Meta Ads + WhatsApp automation. Waiting on owner approval — she travels a lot.",
    phone: "+20 122 567 8901",
    email: "dina@azizglow.com",
    createdAt: getDateInMonth(5),
  },
  {
    id: "lead-017",
    clientName: "Amir Youssef - Law Firm",
    niche: "Legal Services",
    sourceAgency: "Freelance",
    status: "Closed",
    dealValue: 20000,
    expectedCommission: 2000,
    nextFollowUpDate: getDateInMonth(22),
    notes:
      "Corporate law firm specializing in real estate disputes. 3-month Google Ads + SEO campaign. Generated 47 qualified leads in first month. Contract renewed.",
    phone: "+20 100 678 9012",
    email: "amir@yousseflaw.com",
    createdAt: getDateInMonth(1),
  },
  {
    id: "lead-018",
    clientName: "Nadia Hassan - Kids Learning Center",
    niche: "Education",
    sourceAgency: "Krijo",
    status: "New Lead",
    dealValue: 16000,
    expectedCommission: 1600,
    nextFollowUpDate: getDateInMonth(14),
    notes:
      "After-school learning center for ages 4-12. Opening 2nd branch in October. Wants full awareness campaign on Facebook + TikTok. Budget confirmed at 16k.",
    phone: "+20 111 345 6789",
    email: "nadia@littleminds.eg",
    createdAt: getDateInMonth(8),
  },
  {
    id: "lead-019",
    clientName: "Khaled Abdel-Rahman - Logistics Co.",
    niche: "Logistics & Supply Chain",
    sourceAgency: "Personal",
    status: "Contacted",
    dealValue: 30000,
    expectedCommission: 3000,
    nextFollowUpDate: getDateInMonth(12),
    notes:
      "Last-mile delivery startup competing with Bosta. Needs brand building and B2B lead generation. Intro call done — awaiting internal budget sign-off.",
    phone: "+20 100 234 8765",
    email: "khaled@fastroute.eg",
    createdAt: getDateInMonth(7),
  },
  {
    id: "lead-020",
    clientName: "Lena Badr - Architecture Firm",
    niche: "Architecture & Real Estate",
    sourceAgency: "Domya",
    status: "Proposal Sent",
    dealValue: 40000,
    expectedCommission: 4000,
    nextFollowUpDate: getDateInMonth(11),
    notes:
      "Award-winning architecture firm entering the residential design market. Proposal covers LinkedIn presence, Houzz optimization, and targeted Meta Ads to high-income segments.",
    phone: "+20 122 456 7890",
    email: "lena@badrarchitects.com",
    createdAt: getDateInMonth(3),
  },
];

export const dummyIncomeEntries: IncomeEntry[] = [
  {
    id: "income-001",
    source: "Sales Agent - Domya (Basic)",
    amount: 6000,
    date: getDateInMonth(1),
    notes: "Monthly basic salary - Domya agency",
  },
  {
    id: "income-002",
    source: "Sales Agent - Krijo (Basic)",
    amount: 10000,
    date: getDateInMonth(1),
    notes: "Monthly basic salary - Krijo agency",
  },
  {
    id: "income-003",
    source: "Pocket money",
    amount: 6000,
    date: getDateInMonth(5),
    notes: "Monthly allowance",
  },
  {
    id: "income-004",
    source: "Commission - Domya",
    amount: 2250,
    date: getDateInMonth(8),
    leadId: "lead-003",
    notes: "Commission from Dr. Laila Karim medical clinic deal",
  },
  {
    id: "income-005",
    source: "Commission - Domya",
    amount: 3800,
    date: getDateInMonth(6),
    leadId: "lead-010",
    notes: "Commission from Rania Ibrahim EdTech platform deal",
  },
  {
    id: "income-006",
    source: "Freelance",
    amount: 2000,
    date: getDateInMonth(9),
    leadId: "lead-017",
    notes: "Commission from Amir Youssef law firm campaign",
  },
  {
    id: "income-007",
    source: "Freelance",
    amount: 8500,
    date: getDateInMonth(4),
    notes: "Website redesign + SEO setup for e-commerce client",
  },
  {
    id: "income-008",
    source: "Freelance",
    amount: 6500,
    date: getDateInMonth(12),
    notes: "Social media strategy consultation & 30-day content calendar",
  },
  {
    id: "income-009",
    source: "Freelance",
    amount: 4200,
    date: getDateInMonth(16),
    notes: "TikTok ads management for fashion brand — 2-week sprint",
  },
  {
    id: "income-010",
    source: "Commission - Krijo",
    amount: 3500,
    date: getDateInMonth(14),
    notes: "Bonus commission for exceeding Q1 target",
  },
  {
    id: "income-011",
    source: "Other",
    amount: 2800,
    date: getDateInMonth(20),
    notes: "Training workshop: Meta Ads for small business owners (8 attendees)",
  },
];
