import { Lead, IncomeEntry } from "./types";

const today = new Date();
const thisMonth = today.getMonth();
const thisYear = today.getFullYear();

const getDateInMonth = (day: number) => {
  return new Date(thisYear, thisMonth, day).toISOString().split("T")[0];
};

export const dummyLeads: Lead[] = [
  {
    id: "lead-001",
    clientName: "Ahmed Hassan - Real Estate Developer",
    niche: "Real Estate Marketing",
    sourceAgency: "Domya",
    status: "Meeting",
    dealValue: 50000,
    expectedCommission: 5000,
    nextFollowUpDate: getDateInMonth(10),
    notes: "Very interested in digital marketing for new compound launch. Meeting scheduled for Q2.",
    phone: "",
    email: "",
    createdAt: getDateInMonth(1),
  },
  {
    id: "lead-002",
    clientName: "Nour Ali - E-commerce Store Owner",
    niche: "E-commerce",
    sourceAgency: "Krijo",
    status: "Proposal Sent",
    dealValue: 35000,
    expectedCommission: 3500,
    nextFollowUpDate: getDateInMonth(12),
    notes: "Sent proposal for Instagram ads and Shopify optimization. Waiting for response.",
    phone: "",
    email: "",
    createdAt: getDateInMonth(3),
  },
  {
    id: "lead-003",
    clientName: "Dr. Laila Karim - Medical Clinic",
    niche: "Healthcare",
    sourceAgency: "Personal",
    status: "Closed",
    dealValue: 15000,
    expectedCommission: 2250,
    nextFollowUpDate: getDateInMonth(15),
    notes: "Completed Facebook and Google Ads campaign. Deal closed successfully!",
    phone: "",
    email: "",
    createdAt: getDateInMonth(2),
  },
  {
    id: "lead-004",
    clientName: "Fatima Mostafa - Fashion Brand",
    niche: "Fashion & Retail",
    sourceAgency: "Krijo",
    status: "Follow-up",
    dealValue: 28000,
    expectedCommission: 2800,
    nextFollowUpDate: getDateInMonth(9),
    notes: "Initial consultation done. Following up on brand strategy proposal.",
    phone: "",
    email: "",
    createdAt: getDateInMonth(4),
  },
  {
    id: "lead-005",
    clientName: "Mohamed Samir - Tech Startup",
    niche: "Technology",
    sourceAgency: "Freelance",
    status: "Contacted",
    dealValue: 42000,
    expectedCommission: 4200,
    nextFollowUpDate: getDateInMonth(11),
    notes: "First contact made via LinkedIn. Interested in growth hacking services.",
    phone: "",
    email: "",
    createdAt: getDateInMonth(5),
  },
  {
    id: "lead-006",
    clientName: "Hana Khalil - Coffee Roastery",
    niche: "Food & Beverage",
    sourceAgency: "Domya",
    status: "New Lead",
    dealValue: 20000,
    expectedCommission: 2000,
    nextFollowUpDate: getDateInMonth(13),
    notes: "Referral from existing client. Wants to expand to online sales.",
    phone: "",
    email: "",
    createdAt: getDateInMonth(6),
  },
  {
    id: "lead-007",
    clientName: "Karim Elsayed - Gym Chain",
    niche: "Fitness & Wellness",
    sourceAgency: "Personal",
    status: "Proposal Sent",
    dealValue: 32000,
    expectedCommission: 3200,
    nextFollowUpDate: getDateInMonth(14),
    notes: "Sent comprehensive digital marketing proposal for 3 branches expansion.",
    phone: "",
    email: "",
    createdAt: getDateInMonth(1),
  },
  {
    id: "lead-008",
    clientName: "Yasmin Adel - Interior Design Studio",
    niche: "Interior Design",
    sourceAgency: "Domya",
    status: "Lost",
    dealValue: 18000,
    expectedCommission: 0,
    nextFollowUpDate: getDateInMonth(16),
    notes: "Client chose competitor. Great learning opportunity.",
    phone: "",
    email: "",
    createdAt: getDateInMonth(2),
  },
];

export const dummyIncomeEntries: IncomeEntry[] = [
  {
    id: "income-001",
    source: "Sales Agent - Domya (Basic)",
    amount: 6000,
    date: getDateInMonth(1),
    notes: "Monthly basic income - May 2026",
  },
  {
    id: "income-002",
    source: "Sales Agent - Krijo (Basic)",
    amount: 10000,
    date: getDateInMonth(1),
    notes: "Monthly basic income - May 2026",
  },
  {
    id: "income-003",
    source: "Pocket money",
    amount: 6000,
    date: getDateInMonth(5),
    notes: "Monthly allowance",
  },
  {
    id: "income-004",
    source: "Commission - Domya",
    amount: 2250,
    date: getDateInMonth(8),
    leadId: "lead-003",
    notes: "Commission from Dr. Laila Karim medical clinic deal",
  },
  {
    id: "income-005",
    source: "Freelance",
    amount: 8000,
    date: getDateInMonth(6),
    notes: "Website design project for tech startup",
  },
  {
    id: "income-006",
    source: "Freelance",
    amount: 6500,
    date: getDateInMonth(12),
    notes: "Social media strategy consultation",
  },
];
